### ISSUE TITLE
Error running tests in install process

### ISSUE THREAD

**Issue by bobappleyard** [llvmpy/llvmpy#133]
I followed the quick start instructions on llvmpy.org

Everything seemed to go okay, but at step 4 I got this error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "llvm/__init__.py", line 7, in <module>
    from llvmpy import extra
  File "llvmpy/extra.py", line 5, in <module>
    from llvmpy import capsule
  File "llvmpy/capsule.py", line 4, in <module>
    from llvmpy._capsule import (unwrap, has_ownership, downcast, wrap,
ImportError: No module named _capsule

This is when trying to "import llvm"

**Comment by sklam** [comment]
If you are following the guide exactly, you are likely to be in the source directory.  Python is importing the local 'llvm' directory which does not contain the C-extensions.  You will need to leave the source directory so that Python will import from the installed directory (usually the "site-packages").  

In addition, I highly recommend using llvmlite (https://github.com/numba/llvmlite) instead.  It is developed by llvmpy maintainers and numba developers to replace llvmpy.  Llvmpy is no longer maintained.

**Comment by bobappleyard** [comment]
Oh right. Thanks.
